import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import MenuAnt from '@/components/MenuAnt'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <nav className={styles.boxSup}>
          <div className={styles.boxSup_logo}>logo</div>
          <div className={styles.boxSup_menu}>
            <MenuAnt></MenuAnt>
          </div>
        </nav>

        <section className={styles.boxMedio}>
          <div className={styles.boxMedio_filtros}>filtros</div> {/* Aside? */}
          <div className={styles.boxMedio_personas}>personas</div>
          <div className={styles.boxMedio_equipo}>mi equipo</div>
        </section>

        <footer className={styles.boxInf}>
          Footer
        </footer>

      </main>
    </>
  )
}
